### ISSUE TITLE
Merge npm branch with master

### ISSUE THREAD

**Issue by LydiaFrance** [tgve/eAtlas#92] opened 2022-01-14 12:52 UTC

**Comment by layik** [comment] 2022-01-14 14:04
Thanks @LydiaFrance and @rolyp. 

One thing that is prevented/preventing me from making my mind  up is [tgve/eatlas-template](https://github.com/tgve/eatlas-template/) and [tgve/full-template](https://github.com/tgve/full-template) in terms of what a master branch should look like. Say we rename this repo as `tgvejs` (i.e this repository becomes the "source of truth"), then we would either keep those repositories or move them into an "example" folder in the same `npmjs` repo and possibly build those as the GH pages output.

If we do keep them, and so far I am inclined towards this, as they are now, then maybe I need to just propose to rename `master` as `master-old` and rename `npm` as master. The importance of those two repositories can be documented, if not already, with their reasons.

Any thoughts on this would be great for me. Thanks

**Comment by layik** [comment] 2022-01-14 14:06
`master` or `main` for me is not an issue.

**Comment by rolyp** [comment] 2022-01-14 14:38
Duplicate of #64

**Closed by rolyp** 2022-01-14 14:38 UTC
