### ISSUE TITLE
Replace `master` branch by `npm`

### ISSUE THREAD

**Issue by layik** [tgve/eAtlas#64] opened 2021-09-15 09:22 UTC
- [x] remove references to “the main repo” in `eAtlas`
- [x] check in with @layik re. unpublished commits on `master`
- [x] rename `master` -> old
- [x] delete `old`

Done/dropped:
- [x] make `npm` the default branch
- [x] delete `build` and `start` scripts from `package.json`
- [x] delete `wip` branch
- [x] #107 
- [x] delete `letsbeatcovid` and `covid19`
- [x] rename `npm` to (e.g.) `release` and `npm-dev` to `develop`

> This is mainly to keep using GH functionality such as automatic issue closing etc.
> 
> The npm development is the way forward. ~However, the original `fork` is useful for people who might want to use it the way the original work was done.~ Now is the time for a new master/main branch.
> 
> Imported from #96:
>
> For clarification, the branch was the main dev repo for eAtlas/TGVE and has now grown out of its purpose.
> 
> - master branch is now way behind branch `npm`
> - branch `npm` is the most important part, `npm-dev` is where I do work and create PRs on `npm`.
> - Wiki is the main docs for "the project"
> - Dockerfile is based on "old" approach of building the front-end using JS tools (npm)
>
> Must be done:
> - README to serve as pointer to Wiki/docs and other repo docs etc
> - master branch => `npm` branch?
> - etc
> 
> Consider doing:
> - ??

**Comment by layik** [comment] 2022-01-14 13:32
#92

**Comment by rolyp** [comment] 2022-01-14 14:38
Closing #92 as a duplicate of this. Importing comment from that issue by @layik:

> Thanks @LydiaFrance and @rolyp. 
>
> One thing that is prevented/preventing me from making my mind  up is [tgve/eatlas-template](https://github.com/tgve/eatlas-template/) and [tgve/full-template](https://github.com/tgve/full-template) in terms of what a master branch should look like. Say we rename this repo as `tgvejs` (i.e this repository becomes the "source of truth"), then we would either keep those repositories or move them into an "example" folder in the same `tgvejs` repo and possibly build those as the GH pages output.
>
> If we do keep them, and so far I am inclined towards this, as they are now, then maybe I need to just propose to rename `master` as `master-old` and rename `npm` as master. The importance of those two repositories can be documented, if not already, with their reasons.
>
> Any thoughts on this would be great for me. Thanks

**Comment by rolyp** [comment] 2022-01-16 10:32
@layik Ah, there seem to be commits on `master` that haven't yet been published to `npm`, so things aren't straightforward. In particular `README.md` is quite different on the two branches. Need to discuss.

**Comment by layik** [comment] 2022-01-16 11:03
Indeed!

**Comment by rolyp** [comment] 2022-01-16 11:22
@layik Btw, I will (occasionally) work weird hours, e.g. at weekends. Please ignore any comments that come your way during those unusual hours (unless you wish to respond, of course)!

**Comment by layik** [comment] 2022-01-16 11:53
That makes two of us, glad you gave the warning first.

**Comment by rolyp** [comment] 2022-01-24 14:56
@layik I'll reopen this until we're able to delete `old`.

**Comment by layik** [comment] 2022-01-31 13:16
OK, I have pushed "old" = "master" to private repo for backup only.

**Comment by layik** [comment] 2022-01-31 13:17
Can discuss my action above separately, branch is now deleted.

**Closed** 2022-01-31 13:16 UTC
Labels: build & deploy
